#!/bin/sh
#
# play-track
# by Keith Gaughan <http://talideon.com/>
#
# Think of it as the poor man's MPD. :-) Specifically, I use it for playing
# audio files with ROX. Start it with a file to play that file and without
# to stop whatever the file currently being played from playing.
#
# I, Keith Gaughan, hereby put this script in the public domain. It comes
# without warranty of any kind and the author disclaims responsibility for
# any mishap that may occur due to its use. You are requested, but not
# obligated, to leave the attribution of the original author in place and
# to append your name to the attribution if you distribute altered versions
# of this script.
#

PID_FILE=$HOME/.`basename '$0'`.pid

if [ "$@ " = " " ]; then
	test -r $PID_FILE && kill `cat $PID_FILE` && rm $PID_FILE
else
	test -r $PID_FILE && kill `cat $PID_FILE`
	for i in mplayer mpg321 mpg123 plaympeg; do
		if which $i >/dev/null; then
			$i "$@" >/dev/null &
			PID=$!
			echo $PID >$PID_FILE
			wait $PID && test -r $PID_FILE && rm $PID_FILE
			exit
		fi
	done
fi
