#!/bin/sh
#
# quicksig.sh
# by Keith Gaughan (kmgaughan@eircom.net; http://talideon.com/)
#
# A simple shell script for generating a random email signature.
#
# I, Keith Gaughan, hereby put this script in the public domain. It comes
# without warranty of any kind and the author disclaims responsibility for
# any mishap that may occur due to its use. You are requested, but not
# obligated, to leave the attribution of the original author in place and
# to append your name to the attribution if you distribute altered versions
# of this script.
#

# Configuration for the script: adjust to whatever suits you best.
SIG=$HOME/Data/signatures/signature
QUIPS=$HOME/Data/signatures/quips

# Write out the fixed signature if it exists.
if [ -f $SIG ]; then
	cat $SIG
fi

# Attempt to write out the randomised quip if the database exists.
if [ -f $QUIPS ]; then
	# If the quips index needs rebuilding, rebuild it.
	if [ ! -f $QUIPS.dat ] || [ $QUIPS.dat -ot $QUIPS ]; then
		# For those who are using this for learning, 2>&1 sends all output
		# from stderr (FD 2) to stdout (FD 1), and then sends everything
		# from stdout to the bit bucket so it's not echoed. This ensures
		# strfile's summary never gets displayed.
		strfile $QUIPS 2>&1 >/dev/null
	fi
	fortune $QUIPS
fi
