#!/usr/bin/env python

from __future__ import with_statement
import sys
import os.path

if len(sys.argv) != 3:
    print >> sys.stderr, "Usage: %s <file1> <file2>" % (sys.argv[0],)
    sys.exit(1)
if not os.path.isfile(sys.argv[1]):
    print >> sys.stderr, "First parameter must be a file."
    sys.exit(2)
if not os.path.isfile(sys.argv[2]):
    print >> sys.stderr, "Second parameter must be a file."
    sys.exit(3)

with open(sys.argv[1]) as f1:
    with open(sys.argv[2]) as f2:
        print "\n".join(set(l2.strip() for l2 in f1).difference(l1.strip() for l1 in f2))
